name: todo_list
description: A quick todo list app

version: 0.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite: ^1.1.3
  path_provider: ^0.5.0+1
  google_maps_flutter: ^0.5.0
  rxdart: ^0.21.0

flutter:
  uses-material-design: true

  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # TODO: remove unimported fonts from the assets folder.
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
    - family: Overpass
      fonts:
        - asset: assets/fonts/Overpass/Overpass-Regular.ttf
        - asset: assets/fonts/Overpass/Overpass-Italic.ttf
          style: italic
        - asset: assets/fonts/Overpass/Overpass-Light.ttf
          weight: 300
        - asset: assets/fonts/Overpass/Overpass-Bold.ttf
          weight: 700
